version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - ".github/actions/setup-and-deploy-dashboard"
      - ".github/actions/setup-dashboard-dependencies"
      - ".github/actions/setup-test-dependencies"
    commit-message:
      prefix: "deps(github-actions)"
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "tests"
    commit-message:
      prefix: "deps(python-tests)"
    schedule:
      interval: "monthly"
    target-branch: "main"
    groups:
      python:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "dashboard"
    commit-message:
      prefix: "deps(typescript)"
    schedule:
      interval: "monthly"
    target-branch: "main"
    groups:
      typescript:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "docker/dashboard"
    commit-message:
      prefix: "deps(docker)"
    schedule:
      interval: "monthly"
    target-branch: "main"
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /dashboard
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/dashboard
    schedule:
      interval: daily
