version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - ".github/actions/setup-and-deploy-dashboard"
      - ".github/actions/setup-dashboard-dependencies"
      - ".github/actions/setup-test-dependencies"
    commit-message:
      prefix: "deps(github-actions)"
    schedule:
      interval: "cron"
      cronjob: "30 7,12,17 * * *"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "uv"
    directory: "tests"
    commit-message:
      prefix: "deps(python-tests)"
    schedule:
      interval: "cron"
      cronjob: "30 7,12,17 * * *"
    target-branch: "main"
    groups:
      python:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "dashboard"
    commit-message:
      prefix: "deps(typescript)"
    schedule:
      interval: "cron"
      cronjob: "30 7,12,17 * * *"
    target-branch: "main"
    groups:
      typescript:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "docker"
    directory: "docker/dashboard"
    commit-message:
      prefix: "deps(docker)"
    schedule:
      interval: "cron"
      cronjob: "30 7,12,17 * * *"
    target-branch: "main"
    groups:
      docker:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
