#!/bin/bash
set -x

echo $cwd

# for script in $(ls -1 $current_dir/scripts/*-pre-commit.sh 2> /dev/null); do
#   ts=$SECONDS
#   printf "Running githook: $(echo $script | sed "s;$project_dir/;;g")"
#   $script "$@"
#   te=$(($SECONDS - $ts))
#   printf " (${te}s)\n"
# done
