#!/bin/bash
set +x

echo $cwd
GIT_HOOKS_PATH="githooks/pre-commit-scripts"

for script in $(ls -1 $GIT_HOOKS_PATH 2> /dev/null); do
  ts=$SECONDS
  printf "Running githook: $script"
  bash $GIT_HOOKS_PATH/$script
  te=$(($SECONDS - $ts))
  printf "Script Took (${te}s)\n"
done
