services:
  dashboard:
    container_name: dashboard
    image: github-stats-dashboard
    ports:
      - "8000:80"
    volumes:
      - ../dashboard/out:/var/www/out

  end_to_end_tests:
    container_name: end-to-end-tests
    image: end-to-end-tests
    command: poetry run pytest end_to_end --gherkin-terminal-reporter
    environment:
      - PROJECT_URL=http://host.docker.internal:8000
      - ENVIRONMENT=local
    volumes:
      - ../tests/end_to_end:/end_to_end
