name: "Setup Dependencies"
description: "Installs dependencies for the project"

runs:
  using: "composite"
  steps:
    - name: Set up Just
      uses: extractions/setup-just@v2
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1.7.3
      with:
        chrome-version: 132
        install-chromedriver: true
        install-dependencies: true
    - run: chrome --version
      shell: bash
    - run: chromedriver --version
      shell: bash
    - name: astral-sh/setup-uv
      uses: astral-sh/setup-uv@v5.2.2
    - name: Install Test Python Dependencies
      shell: bash
      run: just tests::install
