name: "Setup Dependencies"
description: "Installs dependencies for the project"

runs:
  using: "composite"
  steps:
    - name: Set up Just
      uses: extractions/setup-just@v2
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1.7.3
      with:
        chrome-version: 132
        install-chromedriver: true
        install-dependencies: true
    - run: chrome --version
      shell: bash
    - run: chromedriver --version
      shell: bash
    - name: Install Python 3.13 with Poetry Cache
      uses: actions/setup-python@v5.4.0
      with:
        python-version-file: "tests/pyproject.toml"
    - name: Install required-version defined in pyproject.toml
      uses: astral-sh/setup-uv@v5.2.2
      with:
        pyproject-file: "tests/pyproject.toml"
    - name: Install Poetry Dependencies
      shell: bash
      run: just tests::install
