name: "Setup Dependencies"
description: "Installs dependencies for the project"

runs:
  using: "composite"
  steps:
    - name: Set up Just
      uses: extractions/setup-just@v2

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1.7.2
      with:
        chrome-version: 129
        install-chromedriver: true
        install-dependencies: true

    - run: chrome --version
      shell: bash

    - run: chromedriver --version
      shell: bash

    - name: Install Poetry
      shell: bash
      run: pipx install poetry

    - name: Install Python 3.13 with Poetry Cache
      uses: actions/setup-python@v5.2.0
      with:
        python-version-file: "tests/pyproject.toml"
        cache: "poetry"

    - name: Install Poetry Dependencies
      shell: bash
      run: just tests::install
