name: Clean Caches

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions: {}

jobs:
  clean-caches:
    name: Clean Caches
    permissions:
      contents: read
    uses: JackPlowman/reusable-workflows/.github/workflows/common-clean-caches.yml@9a9f81499295e2225552c5fd130369a2a02cb908 # v2025.08.15.01
    secrets:
      workflow_github_token: ${{ secrets.GH_TOKEN }}
