name: Deploy Preview to GitHub Pages

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup and Deploy Dashboard
        uses: ./.github/actions/setup-and-deploy-dashboard
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test-deployment:
    name: Test GitHub Pages Deployment
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Test Dependencies
        uses: ./.github/actions/setup-test-dependencies

      - name: Run tests
        run: just tests::run
        env:
          HEADLESS: true

  revert-to-main:
    name: Build Main
    runs-on: ubuntu-latest
    if: failure()
    needs: test-deployment

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v5.1.0
        with:
          name: github-pages

      - name: Checkout main
        run: git checkout main

      - name: Setup and Deploy Dashboard
        uses: ./.github/actions/setup-and-deploy-dashboard
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
